### ISSUE TITLE
Failed to load the omnisharp-atom package

### ISSUE THREAD

**Issue by usersxm** [OmniSharp/omnisharp-atom#97]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.2.1

### Stack Trace

Failed to load the omnisharp-atom package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/julio/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni-sharp-server.coffee:37:10
    at Object.<anonymous> (/Users/piasentini/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni-sharp-server.coffee:158:5)
    at Object.<anonymous> (/Users/piasentini/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni-sharp-server.coffee:160:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/piasentini/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/status-bar-view.coffee:11:21)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
omnisharp-atom, v0.2.1

# Dev
No dev packages
```

**Comment by willl** [comment]
Hi @usersxm, v0.3.0 of OmniSharp Atom was recently released. Can you see if this is still an issue you're having with the latest version?

Thanks.

**Comment by david-driscoll** [comment]
@usersxm we have pushed a few large updates, let us know if you're still having an issue with the latest versions of atom and omnisharp-atom.

Thanks!

**Comment by hmemcpy** [comment]
Got the same error after updating to 0.4.30 just now, Atom 0.199.0.

Stack trace:
```
Error: L3: Declaration or statement expected.
L3: ';' expected.
    at TypeScriptSimple.toJavaScript (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\typescript-simple\index.js:118:23)
    at TypeScriptSimple.compile (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\typescript-simple\index.js:50:25)
    at transpile (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\typescript.js:86:14)
    at Object.loadFile [as .ts] (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\typescript.js:98:67)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:5:12)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .ts] (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\typescript.js:99:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:707:34)
```
